"""initial schema

Revision ID: 1cc688d8ae37
Revises: 
Create Date: 2026-06-02 05:11:54.436694
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cc688d8ae37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ab_test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_a_id', sa.Integer(), nullable=True),
    sa.Column('strategy_b_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('winner', sa.String(length=16), nullable=False),
    sa.Column('a_metrics', sa.JSON(), nullable=False),
    sa.Column('b_metrics', sa.JSON(), nullable=False),
    sa.Column('a_fitness', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('b_fitness', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('p_value', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ab_test_results_created_at'), 'ab_test_results', ['created_at'], unique=False)
    op.create_table('account_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('quote_currency', sa.String(length=16), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('available_balance', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('locked_balance', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('positions_value', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('balances', sa.JSON(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_snapshots_created_at'), 'account_snapshots', ['created_at'], unique=False)
    op.create_index(op.f('ix_account_snapshots_exchange'), 'account_snapshots', ['exchange'], unique=False)
    op.create_table('backtest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('initial_cash', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('charts', sa.JSON(), nullable=False),
    sa.Column('optimization_results', sa.JSON(), nullable=False),
    sa.Column('walk_forward_results', sa.JSON(), nullable=False),
    sa.Column('monte_carlo_results', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_runs_symbol'), 'backtest_runs', ['symbol'], unique=False)
    op.create_table('circuit_breaker_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('scope', sa.String(length=32), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('triggered_value', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('triggered_by', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_circuit_breaker_events_created_at'), 'circuit_breaker_events', ['created_at'], unique=False)
    op.create_table('data_quality_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_candles', sa.Integer(), nullable=False),
    sa.Column('valid_candles', sa.Integer(), nullable=False),
    sa.Column('anomalies_total', sa.Integer(), nullable=False),
    sa.Column('missing_candles', sa.Integer(), nullable=False),
    sa.Column('average_health_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('anomaly_breakdown', sa.JSON(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_quality_reports_created_at'), 'data_quality_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_data_quality_reports_symbol'), 'data_quality_reports', ['symbol'], unique=False)
    op.create_index(op.f('ix_data_quality_reports_timeframe'), 'data_quality_reports', ['timeframe'], unique=False)
    op.create_table('execution_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slippage_avg', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('slippage_std', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('latency_signal_submit_ms', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('latency_submit_ack_ms', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('latency_ack_fill_ms', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('latency_total_execution_ms', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('fill_completion_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('partial_fill_ratio', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('execution_quality_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_metrics_strategy_name'), 'execution_metrics', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_execution_metrics_timestamp'), 'execution_metrics', ['timestamp'], unique=False)
    op.create_table('execution_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('total_fills', sa.Integer(), nullable=False),
    sa.Column('average_slippage_pct', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('average_latency_ms', sa.Numeric(precision=12, scale=4), nullable=False),
    sa.Column('average_quality_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('sharpe_decay', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('slippage_cost_usd', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_reports_created_at'), 'execution_reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_execution_reports_strategy_name'), 'execution_reports', ['strategy_name'], unique=False)
    op.create_table('feature_store',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('importance_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('correlation_with_profit', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('stability_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('feature_metadata', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_store_category'), 'feature_store', ['category'], unique=False)
    op.create_index(op.f('ix_feature_store_name'), 'feature_store', ['name'], unique=False)
    op.create_index(op.f('ix_feature_store_symbol'), 'feature_store', ['symbol'], unique=False)
    op.create_index(op.f('ix_feature_store_updated_at'), 'feature_store', ['updated_at'], unique=False)
    op.create_table('historical_candles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('high', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('low', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('close', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', name='uq_candle_symbol_tf_ts')
    )
    op.create_index(op.f('ix_historical_candles_symbol'), 'historical_candles', ['symbol'], unique=False)
    op.create_index(op.f('ix_historical_candles_timeframe'), 'historical_candles', ['timeframe'], unique=False)
    op.create_index(op.f('ix_historical_candles_timestamp'), 'historical_candles', ['timestamp'], unique=False)
    op.create_table('hypothesis_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('statement', sa.Text(), nullable=False),
    sa.Column('feature', sa.String(length=64), nullable=False),
    sa.Column('condition', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('supported', sa.Boolean(), nullable=False),
    sa.Column('edge', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('p_value', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('sample_size', sa.Integer(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypothesis_tests_created_at'), 'hypothesis_tests', ['created_at'], unique=False)
    op.create_index(op.f('ix_hypothesis_tests_feature'), 'hypothesis_tests', ['feature'], unique=False)
    op.create_index(op.f('ix_hypothesis_tests_status'), 'hypothesis_tests', ['status'], unique=False)
    op.create_table('learning_cycles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('patterns_found', sa.Integer(), nullable=False),
    sa.Column('hypotheses_generated', sa.Integer(), nullable=False),
    sa.Column('features_discovered', sa.Integer(), nullable=False),
    sa.Column('strategies_evolved', sa.Integer(), nullable=False),
    sa.Column('strategies_validated', sa.Integer(), nullable=False),
    sa.Column('promotion_requests', sa.Integer(), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_cycles_started_at'), 'learning_cycles', ['started_at'], unique=False)
    op.create_index(op.f('ix_learning_cycles_status'), 'learning_cycles', ['status'], unique=False)
    op.create_table('learning_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('patterns_learned', sa.Integer(), nullable=False),
    sa.Column('failed_strategies', sa.Integer(), nullable=False),
    sa.Column('new_candidates', sa.Integer(), nullable=False),
    sa.Column('promotion_requests', sa.Integer(), nullable=False),
    sa.Column('report_data', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learning_reports_created_at'), 'learning_reports', ['created_at'], unique=False)
    op.create_table('market_data_anomalies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('anomaly_type', sa.String(length=48), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('detection_method', sa.String(length=32), nullable=False),
    sa.Column('observed_value', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('repair_action', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_anomalies_anomaly_type'), 'market_data_anomalies', ['anomaly_type'], unique=False)
    op.create_index(op.f('ix_market_data_anomalies_created_at'), 'market_data_anomalies', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_data_anomalies_symbol'), 'market_data_anomalies', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_data_anomalies_timeframe'), 'market_data_anomalies', ['timeframe'], unique=False)
    op.create_index(op.f('ix_market_data_anomalies_timestamp'), 'market_data_anomalies', ['timestamp'], unique=False)
    op.create_table('market_data_clean',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('high', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('low', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('close', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('repair_action', sa.String(length=32), nullable=False),
    sa.Column('is_uncertain', sa.Boolean(), nullable=False),
    sa.Column('health_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', 'source', name='uq_mdq_clean')
    )
    op.create_index(op.f('ix_market_data_clean_created_at'), 'market_data_clean', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_data_clean_symbol'), 'market_data_clean', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_data_clean_timeframe'), 'market_data_clean', ['timeframe'], unique=False)
    op.create_index(op.f('ix_market_data_clean_timestamp'), 'market_data_clean', ['timestamp'], unique=False)
    op.create_table('market_data_health_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('health_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('consistency_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('completeness_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('anomaly_inverse_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('latency_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('category', sa.String(length=16), nullable=False),
    sa.Column('trade_status', sa.String(length=16), nullable=False),
    sa.Column('candles_evaluated', sa.Integer(), nullable=False),
    sa.Column('anomalies_found', sa.Integer(), nullable=False),
    sa.Column('missing_candles', sa.Integer(), nullable=False),
    sa.Column('feed_latency_ms', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_data_health_logs_created_at'), 'market_data_health_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_data_health_logs_symbol'), 'market_data_health_logs', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_data_health_logs_timeframe'), 'market_data_health_logs', ['timeframe'], unique=False)
    op.create_table('market_data_raw',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('data_type', sa.String(length=16), nullable=False),
    sa.Column('open', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('high', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('low', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('close', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('volume', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'timeframe', 'timestamp', 'source', name='uq_mdq_raw')
    )
    op.create_index(op.f('ix_market_data_raw_created_at'), 'market_data_raw', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_data_raw_symbol'), 'market_data_raw', ['symbol'], unique=False)
    op.create_index(op.f('ix_market_data_raw_timeframe'), 'market_data_raw', ['timeframe'], unique=False)
    op.create_index(op.f('ix_market_data_raw_timestamp'), 'market_data_raw', ['timestamp'], unique=False)
    op.create_table('market_regimes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('regime_type', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('rule_based_vote', sa.String(length=32), nullable=False),
    sa.Column('clustering_vote', sa.String(length=32), nullable=False),
    sa.Column('ml_vote', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_regimes_created_at'), 'market_regimes', ['created_at'], unique=False)
    op.create_index(op.f('ix_market_regimes_symbol'), 'market_regimes', ['symbol'], unique=False)
    op.create_table('paper_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('initial_balance', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('max_daily_loss_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('max_drawdown_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('max_exposure_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('max_open_positions', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('daily_max_risk_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('weekly_max_risk_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('monthly_max_risk_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('entry_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('take_profit', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('trailing_stop', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_positions_symbol'), 'positions', ['symbol'], unique=False)
    op.create_table('promotion_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('ranking_score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('gate_passed', sa.Boolean(), nullable=False),
    sa.Column('gate_reasons', sa.JSON(), nullable=False),
    sa.Column('validation', sa.JSON(), nullable=False),
    sa.Column('requested_by', sa.String(length=64), nullable=False),
    sa.Column('decided_by', sa.String(length=128), nullable=True),
    sa.Column('decision_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_promotion_requests_created_at'), 'promotion_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_promotion_requests_status'), 'promotion_requests', ['status'], unique=False)
    op.create_index(op.f('ix_promotion_requests_strategy_id'), 'promotion_requests', ['strategy_id'], unique=False)
    op.create_table('regime_confidence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('confidence_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('vote_weights', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regime_confidence_symbol'), 'regime_confidence', ['symbol'], unique=False)
    op.create_index(op.f('ix_regime_confidence_timestamp'), 'regime_confidence', ['timestamp'], unique=False)
    op.create_table('regime_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('features_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regime_features_symbol'), 'regime_features', ['symbol'], unique=False)
    op.create_index(op.f('ix_regime_features_timestamp'), 'regime_features', ['timestamp'], unique=False)
    op.create_table('regime_performance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('regime_type', sa.String(length=32), nullable=False),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('winning_trades', sa.Integer(), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('total_pnl', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('drawdown', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regime_performance_regime_type'), 'regime_performance', ['regime_type'], unique=False)
    op.create_index(op.f('ix_regime_performance_strategy_name'), 'regime_performance', ['strategy_name'], unique=False)
    op.create_table('regime_transitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('old_regime', sa.String(length=32), nullable=False),
    sa.Column('new_regime', sa.String(length=32), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('trigger_event', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regime_transitions_created_at'), 'regime_transitions', ['created_at'], unique=False)
    op.create_index(op.f('ix_regime_transitions_symbol'), 'regime_transitions', ['symbol'], unique=False)
    op.create_table('research_strategies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('template', sa.String(length=64), nullable=False),
    sa.Column('signature', sa.String(length=512), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('origin', sa.String(length=32), nullable=False),
    sa.Column('family_id', sa.Integer(), nullable=True),
    sa.Column('best_fitness', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('best_version_id', sa.Integer(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_strategies_created_at'), 'research_strategies', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_strategies_family_id'), 'research_strategies', ['family_id'], unique=False)
    op.create_index(op.f('ix_research_strategies_name'), 'research_strategies', ['name'], unique=False)
    op.create_index(op.f('ix_research_strategies_signature'), 'research_strategies', ['signature'], unique=True)
    op.create_index(op.f('ix_research_strategies_status'), 'research_strategies', ['status'], unique=False)
    op.create_table('strategy_alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('alert_level', sa.String(length=16), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_taken', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_alerts_created_at'), 'strategy_alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_alerts_strategy_name'), 'strategy_alerts', ['strategy_name'], unique=False)
    op.create_table('strategy_baselines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('expected_sharpe', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('expected_win_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('expected_profit_factor', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('expected_drawdown', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('expected_trade_frequency', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_baselines_strategy_name'), 'strategy_baselines', ['strategy_name'], unique=True)
    op.create_table('strategy_drift_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('drift_score', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('deviation_details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_drift_scores_created_at'), 'strategy_drift_scores', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_drift_scores_strategy_name'), 'strategy_drift_scores', ['strategy_name'], unique=False)
    op.create_table('strategy_health_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('rolling_sharpe', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('rolling_win_rate', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('rolling_profit_factor', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('rolling_drawdown', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('expectancy', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('health_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_health_logs_created_at'), 'strategy_health_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_health_logs_strategy_name'), 'strategy_health_logs', ['strategy_name'], unique=False)
    op.create_table('strategy_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_capital_per_trade_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('daily_max_loss_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('weekly_max_loss_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('max_open_positions', sa.Integer(), nullable=False),
    sa.Column('min_reward_risk', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('atr_multiplier', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('trailing_stop_pct', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('strategy_state_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('old_state', sa.String(length=32), nullable=False),
    sa.Column('new_state', sa.String(length=32), nullable=False),
    sa.Column('trigger_reason', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_state_history_created_at'), 'strategy_state_history', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_state_history_strategy_name'), 'strategy_state_history', ['strategy_name'], unique=False)
    op.create_table('system_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('walkforward_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('mode', sa.String(length=32), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('train_period_days', sa.Integer(), nullable=False),
    sa.Column('test_period_days', sa.Integer(), nullable=False),
    sa.Column('step_days', sa.Integer(), nullable=False),
    sa.Column('n_trials', sa.Integer(), nullable=False),
    sa.Column('initial_cash', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('aggregated_metrics', sa.JSON(), nullable=False),
    sa.Column('combined_equity_curve', sa.JSON(), nullable=False),
    sa.Column('monte_carlo_results', sa.JSON(), nullable=False),
    sa.Column('deployment_decision', sa.JSON(), nullable=False),
    sa.Column('overfit_warnings', sa.JSON(), nullable=False),
    sa.Column('report', sa.JSON(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_walkforward_runs_symbol'), 'walkforward_runs', ['symbol'], unique=False)
    op.create_table('allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=False),
    sa.Column('target_name', sa.String(length=128), nullable=False),
    sa.Column('weight', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('performance_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('risk_adjusted_return', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('correlation_penalty', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('stability_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('drawdown_adjustment', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('exchange', sa.String(length=32), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=False),
    sa.Column('api_secret_encrypted', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('backtest_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('entry_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exit_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('entry_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('exit_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('fee', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('pnl', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('pnl_pct', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('exit_reason', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['backtest_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_backtest_trades_symbol'), 'backtest_trades', ['symbol'], unique=False)
    op.create_table('discovered_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=96), nullable=False),
    sa.Column('formula', sa.String(length=255), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('correlation_with_profit', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('importance_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('stability_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['learning_cycles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_discovered_features_created_at'), 'discovered_features', ['created_at'], unique=False)
    op.create_index(op.f('ix_discovered_features_name'), 'discovered_features', ['name'], unique=False)
    op.create_index(op.f('ix_discovered_features_symbol'), 'discovered_features', ['symbol'], unique=False)
    op.create_table('knowledge_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('knowledge_type', sa.String(length=16), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('regime', sa.String(length=32), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=6, scale=4), nullable=False),
    sa.Column('support', sa.Integer(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['learning_cycles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_entries_created_at'), 'knowledge_entries', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_knowledge_type'), 'knowledge_entries', ['knowledge_type'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_regime'), 'knowledge_entries', ['regime'], unique=False)
    op.create_index(op.f('ix_knowledge_entries_symbol'), 'knowledge_entries', ['symbol'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_order_id', sa.String(length=128), nullable=True),
    sa.Column('position_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('raw_response', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_exchange_order_id'), 'orders', ['exchange_order_id'], unique=False)
    op.create_index(op.f('ix_orders_symbol'), 'orders', ['symbol'], unique=False)
    op.create_table('paper_equity_curve',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('cash_balance', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('equity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('drawdown', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('exposure', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_equity_curve_timestamp'), 'paper_equity_curve', ['timestamp'], unique=False)
    op.create_table('paper_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('event', sa.String(length=64), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('paper_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('order_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('requested_quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('filled_quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('average_fill_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('limit_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('stop_price', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('fee_paid', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('signal', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('filled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_orders_symbol'), 'paper_orders', ['symbol'], unique=False)
    op.create_table('paper_positions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('average_entry_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('last_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('stop_loss', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=24, scale=10), nullable=True),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_positions_symbol'), 'paper_positions', ['symbol'], unique=False)
    op.create_table('portfolio_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('position_size', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('average_entry_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('current_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('unrealized_pnl', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('risk_contribution', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_assets_symbol'), 'portfolio_assets', ['symbol'], unique=False)
    op.create_table('portfolio_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_equity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('sharpe_ratio', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('drawdown', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('correlation_risk_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('exposure_per_asset', sa.JSON(), nullable=False),
    sa.Column('exposure_per_strategy', sa.JSON(), nullable=False),
    sa.Column('volatility_adjusted_return', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_metrics_timestamp'), 'portfolio_metrics', ['timestamp'], unique=False)
    op.create_table('rebalance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('trigger_reason', sa.String(length=64), nullable=False),
    sa.Column('previous_weights', sa.JSON(), nullable=False),
    sa.Column('new_weights', sa.JSON(), nullable=False),
    sa.Column('execution_log', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_jti'), 'refresh_tokens', ['jti'], unique=True)
    op.create_index(op.f('ix_refresh_tokens_revoked'), 'refresh_tokens', ['revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('research_experiments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('experiment_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('timeframe', sa.String(length=8), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('result', sa.JSON(), nullable=False),
    sa.Column('fitness', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['strategy_id'], ['research_strategies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_research_experiments_created_at'), 'research_experiments', ['created_at'], unique=False)
    op.create_index(op.f('ix_research_experiments_experiment_type'), 'research_experiments', ['experiment_type'], unique=False)
    op.create_index(op.f('ix_research_experiments_status'), 'research_experiments', ['status'], unique=False)
    op.create_table('risk_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('portfolio_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('scenario_name', sa.String(length=64), nullable=False),
    sa.Column('simulated_loss', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('limit_status', sa.String(length=32), nullable=False),
    sa.Column('metrics_snapshot', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_snapshots_timestamp'), 'risk_snapshots', ['timestamp'], unique=False)
    op.create_table('strategy_rankings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=True),
    sa.Column('score', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('robustness', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('walk_forward', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('stability', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('sharpe', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('drawdown', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('cycle_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['cycle_id'], ['learning_cycles.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_rankings_created_at'), 'strategy_rankings', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_rankings_score'), 'strategy_rankings', ['score'], unique=False)
    op.create_index(op.f('ix_strategy_rankings_strategy_id'), 'strategy_rankings', ['strategy_id'], unique=False)
    op.create_table('strategy_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('walk_forward', sa.JSON(), nullable=False),
    sa.Column('monte_carlo', sa.JSON(), nullable=False),
    sa.Column('sharpe', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('stability_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('consistency_score', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('fitness', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('overfit', sa.Boolean(), nullable=False),
    sa.Column('total_trades', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['strategy_id'], ['research_strategies.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_strategy_versions_created_at'), 'strategy_versions', ['created_at'], unique=False)
    op.create_index(op.f('ix_strategy_versions_fitness'), 'strategy_versions', ['fitness'], unique=False)
    op.create_table('walkforward_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('run_id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('train_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('train_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('test_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('test_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('best_params', sa.JSON(), nullable=False),
    sa.Column('train_metrics', sa.JSON(), nullable=False),
    sa.Column('test_metrics', sa.JSON(), nullable=False),
    sa.Column('equity_curve', sa.JSON(), nullable=False),
    sa.Column('trades', sa.JSON(), nullable=False),
    sa.Column('wfe', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('overfit_warning', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['walkforward_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_walkforward_windows_window_id'), 'walkforward_windows', ['window_id'], unique=False)
    op.create_table('execution_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('strategy_name', sa.String(length=128), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('paper_order_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('order_type', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('expected_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('expected_quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('signal_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submission_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['paper_order_id'], ['paper_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_orders_created_at'), 'execution_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_execution_orders_strategy_name'), 'execution_orders', ['strategy_name'], unique=False)
    op.create_index(op.f('ix_execution_orders_symbol'), 'execution_orders', ['symbol'], unique=False)
    op.create_table('paper_trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('fee', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('traded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['paper_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_id'], ['paper_orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paper_trades_symbol'), 'paper_trades', ['symbol'], unique=False)
    op.create_table('reconciliation_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('exchange_order_id', sa.String(length=128), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('previous_status', sa.String(length=32), nullable=True),
    sa.Column('new_status', sa.String(length=32), nullable=True),
    sa.Column('filled_quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_logs_created_at'), 'reconciliation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_reconciliation_logs_exchange_order_id'), 'reconciliation_logs', ['exchange_order_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_logs_symbol'), 'reconciliation_logs', ['symbol'], unique=False)
    op.create_table('trades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=True),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('side', sa.String(length=16), nullable=False),
    sa.Column('price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('fee', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('realized_pnl', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('traded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trades_symbol'), 'trades', ['symbol'], unique=False)
    op.create_table('execution_fills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_order_id', sa.Integer(), nullable=False),
    sa.Column('fill_price', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('fill_quantity', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('fee', sa.Numeric(precision=24, scale=10), nullable=False),
    sa.Column('fill_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('slippage', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_order_id'], ['execution_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_execution_fills_created_at'), 'execution_fills', ['created_at'], unique=False)
    op.create_table('latency_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_order_id', sa.Integer(), nullable=False),
    sa.Column('signal_generation_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('order_submission_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exchange_ack_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('fill_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('signal_to_submit_ms', sa.Integer(), nullable=False),
    sa.Column('submit_to_ack_ms', sa.Integer(), nullable=False),
    sa.Column('ack_to_fill_ms', sa.Integer(), nullable=False),
    sa.Column('total_execution_delay_ms', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_order_id'], ['execution_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_latency_logs_created_at'), 'latency_logs', ['created_at'], unique=False)
    op.create_table('slippage_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('execution_order_id', sa.Integer(), nullable=False),
    sa.Column('slippage_pct', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('slippage_category', sa.String(length=32), nullable=False),
    sa.Column('volatility_rolling', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('spread', sa.Numeric(precision=12, scale=6), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_order_id'], ['execution_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_slippage_logs_created_at'), 'slippage_logs', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_slippage_logs_created_at'), table_name='slippage_logs')
    op.drop_table('slippage_logs')
    op.drop_index(op.f('ix_latency_logs_created_at'), table_name='latency_logs')
    op.drop_table('latency_logs')
    op.drop_index(op.f('ix_execution_fills_created_at'), table_name='execution_fills')
    op.drop_table('execution_fills')
    op.drop_index(op.f('ix_trades_symbol'), table_name='trades')
    op.drop_table('trades')
    op.drop_index(op.f('ix_reconciliation_logs_symbol'), table_name='reconciliation_logs')
    op.drop_index(op.f('ix_reconciliation_logs_exchange_order_id'), table_name='reconciliation_logs')
    op.drop_index(op.f('ix_reconciliation_logs_created_at'), table_name='reconciliation_logs')
    op.drop_table('reconciliation_logs')
    op.drop_index(op.f('ix_paper_trades_symbol'), table_name='paper_trades')
    op.drop_table('paper_trades')
    op.drop_index(op.f('ix_execution_orders_symbol'), table_name='execution_orders')
    op.drop_index(op.f('ix_execution_orders_strategy_name'), table_name='execution_orders')
    op.drop_index(op.f('ix_execution_orders_created_at'), table_name='execution_orders')
    op.drop_table('execution_orders')
    op.drop_index(op.f('ix_walkforward_windows_window_id'), table_name='walkforward_windows')
    op.drop_table('walkforward_windows')
    op.drop_index(op.f('ix_strategy_versions_fitness'), table_name='strategy_versions')
    op.drop_index(op.f('ix_strategy_versions_created_at'), table_name='strategy_versions')
    op.drop_table('strategy_versions')
    op.drop_index(op.f('ix_strategy_rankings_strategy_id'), table_name='strategy_rankings')
    op.drop_index(op.f('ix_strategy_rankings_score'), table_name='strategy_rankings')
    op.drop_index(op.f('ix_strategy_rankings_created_at'), table_name='strategy_rankings')
    op.drop_table('strategy_rankings')
    op.drop_index(op.f('ix_risk_snapshots_timestamp'), table_name='risk_snapshots')
    op.drop_table('risk_snapshots')
    op.drop_index(op.f('ix_research_experiments_status'), table_name='research_experiments')
    op.drop_index(op.f('ix_research_experiments_experiment_type'), table_name='research_experiments')
    op.drop_index(op.f('ix_research_experiments_created_at'), table_name='research_experiments')
    op.drop_table('research_experiments')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_jti'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('rebalance_events')
    op.drop_index(op.f('ix_portfolio_metrics_timestamp'), table_name='portfolio_metrics')
    op.drop_table('portfolio_metrics')
    op.drop_index(op.f('ix_portfolio_assets_symbol'), table_name='portfolio_assets')
    op.drop_table('portfolio_assets')
    op.drop_index(op.f('ix_paper_positions_symbol'), table_name='paper_positions')
    op.drop_table('paper_positions')
    op.drop_index(op.f('ix_paper_orders_symbol'), table_name='paper_orders')
    op.drop_table('paper_orders')
    op.drop_table('paper_logs')
    op.drop_index(op.f('ix_paper_equity_curve_timestamp'), table_name='paper_equity_curve')
    op.drop_table('paper_equity_curve')
    op.drop_index(op.f('ix_orders_symbol'), table_name='orders')
    op.drop_index(op.f('ix_orders_exchange_order_id'), table_name='orders')
    op.drop_table('orders')
    op.drop_index(op.f('ix_knowledge_entries_symbol'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_regime'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_knowledge_type'), table_name='knowledge_entries')
    op.drop_index(op.f('ix_knowledge_entries_created_at'), table_name='knowledge_entries')
    op.drop_table('knowledge_entries')
    op.drop_index(op.f('ix_discovered_features_symbol'), table_name='discovered_features')
    op.drop_index(op.f('ix_discovered_features_name'), table_name='discovered_features')
    op.drop_index(op.f('ix_discovered_features_created_at'), table_name='discovered_features')
    op.drop_table('discovered_features')
    op.drop_index(op.f('ix_backtest_trades_symbol'), table_name='backtest_trades')
    op.drop_table('backtest_trades')
    op.drop_table('api_keys')
    op.drop_table('allocations')
    op.drop_index(op.f('ix_walkforward_runs_symbol'), table_name='walkforward_runs')
    op.drop_table('walkforward_runs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('system_logs')
    op.drop_index(op.f('ix_strategy_state_history_strategy_name'), table_name='strategy_state_history')
    op.drop_index(op.f('ix_strategy_state_history_created_at'), table_name='strategy_state_history')
    op.drop_table('strategy_state_history')
    op.drop_table('strategy_settings')
    op.drop_index(op.f('ix_strategy_health_logs_strategy_name'), table_name='strategy_health_logs')
    op.drop_index(op.f('ix_strategy_health_logs_created_at'), table_name='strategy_health_logs')
    op.drop_table('strategy_health_logs')
    op.drop_index(op.f('ix_strategy_drift_scores_strategy_name'), table_name='strategy_drift_scores')
    op.drop_index(op.f('ix_strategy_drift_scores_created_at'), table_name='strategy_drift_scores')
    op.drop_table('strategy_drift_scores')
    op.drop_index(op.f('ix_strategy_baselines_strategy_name'), table_name='strategy_baselines')
    op.drop_table('strategy_baselines')
    op.drop_index(op.f('ix_strategy_alerts_strategy_name'), table_name='strategy_alerts')
    op.drop_index(op.f('ix_strategy_alerts_created_at'), table_name='strategy_alerts')
    op.drop_table('strategy_alerts')
    op.drop_index(op.f('ix_research_strategies_status'), table_name='research_strategies')
    op.drop_index(op.f('ix_research_strategies_signature'), table_name='research_strategies')
    op.drop_index(op.f('ix_research_strategies_name'), table_name='research_strategies')
    op.drop_index(op.f('ix_research_strategies_family_id'), table_name='research_strategies')
    op.drop_index(op.f('ix_research_strategies_created_at'), table_name='research_strategies')
    op.drop_table('research_strategies')
    op.drop_index(op.f('ix_regime_transitions_symbol'), table_name='regime_transitions')
    op.drop_index(op.f('ix_regime_transitions_created_at'), table_name='regime_transitions')
    op.drop_table('regime_transitions')
    op.drop_index(op.f('ix_regime_performance_strategy_name'), table_name='regime_performance')
    op.drop_index(op.f('ix_regime_performance_regime_type'), table_name='regime_performance')
    op.drop_table('regime_performance')
    op.drop_index(op.f('ix_regime_features_timestamp'), table_name='regime_features')
    op.drop_index(op.f('ix_regime_features_symbol'), table_name='regime_features')
    op.drop_table('regime_features')
    op.drop_index(op.f('ix_regime_confidence_timestamp'), table_name='regime_confidence')
    op.drop_index(op.f('ix_regime_confidence_symbol'), table_name='regime_confidence')
    op.drop_table('regime_confidence')
    op.drop_index(op.f('ix_promotion_requests_strategy_id'), table_name='promotion_requests')
    op.drop_index(op.f('ix_promotion_requests_status'), table_name='promotion_requests')
    op.drop_index(op.f('ix_promotion_requests_created_at'), table_name='promotion_requests')
    op.drop_table('promotion_requests')
    op.drop_index(op.f('ix_positions_symbol'), table_name='positions')
    op.drop_table('positions')
    op.drop_table('portfolios')
    op.drop_table('paper_accounts')
    op.drop_index(op.f('ix_market_regimes_symbol'), table_name='market_regimes')
    op.drop_index(op.f('ix_market_regimes_created_at'), table_name='market_regimes')
    op.drop_table('market_regimes')
    op.drop_index(op.f('ix_market_data_raw_timestamp'), table_name='market_data_raw')
    op.drop_index(op.f('ix_market_data_raw_timeframe'), table_name='market_data_raw')
    op.drop_index(op.f('ix_market_data_raw_symbol'), table_name='market_data_raw')
    op.drop_index(op.f('ix_market_data_raw_created_at'), table_name='market_data_raw')
    op.drop_table('market_data_raw')
    op.drop_index(op.f('ix_market_data_health_logs_timeframe'), table_name='market_data_health_logs')
    op.drop_index(op.f('ix_market_data_health_logs_symbol'), table_name='market_data_health_logs')
    op.drop_index(op.f('ix_market_data_health_logs_created_at'), table_name='market_data_health_logs')
    op.drop_table('market_data_health_logs')
    op.drop_index(op.f('ix_market_data_clean_timestamp'), table_name='market_data_clean')
    op.drop_index(op.f('ix_market_data_clean_timeframe'), table_name='market_data_clean')
    op.drop_index(op.f('ix_market_data_clean_symbol'), table_name='market_data_clean')
    op.drop_index(op.f('ix_market_data_clean_created_at'), table_name='market_data_clean')
    op.drop_table('market_data_clean')
    op.drop_index(op.f('ix_market_data_anomalies_timestamp'), table_name='market_data_anomalies')
    op.drop_index(op.f('ix_market_data_anomalies_timeframe'), table_name='market_data_anomalies')
    op.drop_index(op.f('ix_market_data_anomalies_symbol'), table_name='market_data_anomalies')
    op.drop_index(op.f('ix_market_data_anomalies_created_at'), table_name='market_data_anomalies')
    op.drop_index(op.f('ix_market_data_anomalies_anomaly_type'), table_name='market_data_anomalies')
    op.drop_table('market_data_anomalies')
    op.drop_index(op.f('ix_learning_reports_created_at'), table_name='learning_reports')
    op.drop_table('learning_reports')
    op.drop_index(op.f('ix_learning_cycles_status'), table_name='learning_cycles')
    op.drop_index(op.f('ix_learning_cycles_started_at'), table_name='learning_cycles')
    op.drop_table('learning_cycles')
    op.drop_index(op.f('ix_hypothesis_tests_status'), table_name='hypothesis_tests')
    op.drop_index(op.f('ix_hypothesis_tests_feature'), table_name='hypothesis_tests')
    op.drop_index(op.f('ix_hypothesis_tests_created_at'), table_name='hypothesis_tests')
    op.drop_table('hypothesis_tests')
    op.drop_index(op.f('ix_historical_candles_timestamp'), table_name='historical_candles')
    op.drop_index(op.f('ix_historical_candles_timeframe'), table_name='historical_candles')
    op.drop_index(op.f('ix_historical_candles_symbol'), table_name='historical_candles')
    op.drop_table('historical_candles')
    op.drop_index(op.f('ix_feature_store_updated_at'), table_name='feature_store')
    op.drop_index(op.f('ix_feature_store_symbol'), table_name='feature_store')
    op.drop_index(op.f('ix_feature_store_name'), table_name='feature_store')
    op.drop_index(op.f('ix_feature_store_category'), table_name='feature_store')
    op.drop_table('feature_store')
    op.drop_index(op.f('ix_execution_reports_strategy_name'), table_name='execution_reports')
    op.drop_index(op.f('ix_execution_reports_created_at'), table_name='execution_reports')
    op.drop_table('execution_reports')
    op.drop_index(op.f('ix_execution_metrics_timestamp'), table_name='execution_metrics')
    op.drop_index(op.f('ix_execution_metrics_strategy_name'), table_name='execution_metrics')
    op.drop_table('execution_metrics')
    op.drop_index(op.f('ix_data_quality_reports_timeframe'), table_name='data_quality_reports')
    op.drop_index(op.f('ix_data_quality_reports_symbol'), table_name='data_quality_reports')
    op.drop_index(op.f('ix_data_quality_reports_created_at'), table_name='data_quality_reports')
    op.drop_table('data_quality_reports')
    op.drop_index(op.f('ix_circuit_breaker_events_created_at'), table_name='circuit_breaker_events')
    op.drop_table('circuit_breaker_events')
    op.drop_index(op.f('ix_backtest_runs_symbol'), table_name='backtest_runs')
    op.drop_table('backtest_runs')
    op.drop_index(op.f('ix_account_snapshots_exchange'), table_name='account_snapshots')
    op.drop_index(op.f('ix_account_snapshots_created_at'), table_name='account_snapshots')
    op.drop_table('account_snapshots')
    op.drop_index(op.f('ix_ab_test_results_created_at'), table_name='ab_test_results')
    op.drop_table('ab_test_results')
    # ### end Alembic commands ###
